### ISSUE TITLE
problems with cython files

### ISSUE THREAD

**Issue by danbek** [proofit404/anaconda-mode#118] opened 2015-09-18 15:42 UTC
When attempting auto-completion on a .pyx file, I'm getting the following error:

error in process filter: Wrong type argument: stringp, ((data . "KeyError(u'cython',)") (code . -32000) (message . "Server error"))

Not sure whether this is a jedi problem or anaconda or something else. I can try to debug further, but I can't even tell where this error message is coming from.

I'm running emacs 24.5 with spacemacs development branch.

**Comment by proofit404** [comment] 2015-09-20 09:16
Can you provide `*anaconda-mode*` content buffer?

**Comment by danbek** [comment] 2015-09-20 17:15
anaconda_mode port 9000
127.0.0.1 - - [20/Sep/2015 11:14:15] ================================================================================
Traceback (most recent call last):
  File "service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'cython\',)"}}')
127.0.0.1 - - [20/Sep/2015 11:14:16] ================================================================================
Traceback (most recent call last):
  File "service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "six.py", line 692, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "KeyError(u\'cython\',)"}}')

**Comment by proofit404** [comment] 2015-09-20 20:30
I need to improve logging layer in the `service-factory` library under `python2`. Until that I can't find root of this problem. Or you can try same sample with `python3`.

**Comment by proofit404** [comment] 2016-02-14 11:03
`Wrong type argument: stringp` is a duplicate of #148.  Since `jedi` doesn't support `cython` syntax the rest of this issue is unrelated to `anaconda-mode`.

**Closed by proofit404** 2016-02-14 11:03 UTC
