### ISSUE TITLE
args-out-of-range error (innocent-ish but noisy) on complete for cv2 package

### ISSUE THREAD

**Issue by olejorgenb** [proofit404/anaconda-mode#174] opened 2016-04-14 14:21 UTC
cv2 is the python bindings for opencv (version 3.0.0)

```
import cv2
cv2.|<wait/trigger completion>
      ^cursor
```

`(args-out-of-range 0 1)` is displayed in minibuffer and no completion candidates are shown

Turning on debug-on-error yields:

```
Debugger entered--Lisp error: (args-out-of-range 0 1)
  put-text-property(0 1 description "module: cv2.cv2" "")
```

"Non empty" completions works
    cv2.hist|<completion>

Not all packages are affected:

```
import numpy as np
np.|<completion>
```

works

The problem seem to be that  `name` in one of the results are empty in `anaconda-mode-complete-extract-names`. Adding guards for empty names around the `(put-text-property 0 1 ... name)` calls fixes the problem, but I guess the real problem might be in the server.

anaconda-mode.el package-Version: 20160411.650
Server: Version: 0.1.1

I use anaconda mode through the spacemacs python layer

**Comment by proofit404** [comment] 2016-04-14 14:43
Thanks for report! I will be able to check this on Sunday. I have very busy schedule until that.

**Comment by twlz0ne** [comment] 2016-09-09 08:07
@proofit404

I have similar problem

Steps:

- launch `emacs -nw`
- switch to `*.py`
- type `.`

Error:

```
Debugger entered--Lisp error: (args-out-of-range "." 1 2)
  match-string(0 ".")
  company-anaconda-prefix()
  company-anaconda(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer *.py> #<window 1 on *.py> 2 2)
  apply(company-idle-begin (#<buffer *.py> #<window 1 on *.py> 2 2))
  timer-event-handler([t 22482 26443 130918 nil company-idle-begin (#<buffer *.py> #<window 1 on *.py> 2 2) nil 0])
```

Environment:

- OS X 10.11.5
- Emacs 25.1.1 rc2

**Comment by twlz0ne** [comment] 2016-09-09 08:09
@proofit404

I have similar problem

Steps:

- launch `emacs -nw`
- switch to `*.py`
- type `.`

Error:

```
Debugger entered--Lisp error: (args-out-of-range "." 1 2)
  match-string(0 ".")
  company-anaconda-prefix()
  company-anaconda(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer *.py> #<window 1 on *.py> 2 2)
  apply(company-idle-begin (#<buffer *.py> #<window 1 on *.py> 2 2))
  timer-event-handler([t 22482 26443 130918 nil company-idle-begin (#<buffer *.py> #<window 1 on *.py> 2 2) nil 0])
```

Environment:

- OS X 10.11.5
- Emacs 25.1.1 rc2

**Comment by proofit404** [comment] 2016-09-09 08:16
Please add python buffer content and anaconda-mode version to your report.

**Comment by twlz0ne** [comment] 2016-09-10 03:03
@proofit404

- Buffer `*.py` is empty
- All packages are up-to-date. anaconda-mode `20160901.1423`, company-anaconda `20160809.705`

Here is my configuration:

```elisp
(require-package 'diminish)
(require 'init-company) ;; from https://github.com/purcell/emacs.d/blob/master/lisp/init-company.el
(require 'init-python-mode) ;; from https://github.com/purcell/emacs.d/blob/master/lisp/init-python-mode.el
(unless window-system
  (remove-hook 'after-init-hook 'company-quickhelp-mode))
```

**Comment by cnglen** [comment] 2016-10-03 01:53
I have the same problem, In test.py, type "a[0]"

Debugger entered--Lisp error: (args-out-of-range "a[0" 127 127)
  match-string(0 "a[0")
  company-anaconda-prefix()
  company-anaconda(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer test.py> #<window 3 on test.py> 37 127)
  apply(company-idle-begin (#<buffer test.py> #<window 3 on test.py> 37 127))
  timer-event-handler([t 22513 47560 61196 nil company-idle-begin (#<buffer test.py> #<window 3 on test.py> 37 127) nil 758000])

**Comment by Atman50** [comment] 2016-10-17 20:07
I have the same error.
Easy to reproduce: 
  1) open a new file foo.py
  2) type:
      def foo(x=1

as soon as you type the '1' the backtrace happens (exactly like the backtraces previous in this thread).

I

**Comment by Atman50** [comment] 2016-10-19 13:07
FWIW, I added a when clause to the string-match in company-anaconda-prefix which seemed to fix the problem and not cause other issues... I could be wrong.

```lisp
(defun company-anaconda-prefix ()
  "Grab prefix at point.
Properly detect strings, comments and attribute access."
  (and anaconda-mode
       (not (company-in-string-or-comment))
       (--if-let (when (or (looking-at "\\_>")
                           (looking-back "\\." (- (point) 1)))
                   (save-match-data
                     (let ((line (buffer-substring-no-properties
                                  (line-beginning-position)
                                  (point))))
                       ;; Here's the added when statement
                       (when (string-match "[a-zA-Z_][a-zA-Z0-9_.]*\\'" line)
                         (match-string 0 line)))))
           (if (looking-back "\\." (- (point) 1))
               (cons it t)
             it)
         'stop)))
```

**Comment by Purring** [comment] 2016-12-03 21:52
**(I came here through google)**
I had this same problem, but the solution above me by Atman50 fixed it. Maybe submit a PR?

Seems like a company-anaconda issue though, not anaconda-mode.

**Comment by Atman50** [comment] 2016-12-04 00:34
Yes, I agree. Company-anaconda.

**Comment by proofit404** [comment] 2016-12-04 18:52
I think the best option is to improve regex used in the prefix function. Can any one prepare test collection of python sources where current implementation fails?

**Comment by Purring** [comment] 2016-12-04 21:10
https://gist.github.com/Purring/3c1bf5ff8f5599de4f1090c886d77d17

here's a gist of the cases ive found. feel free to add to it.

**Comment by proofit404** [comment] 2016-12-05 22:26
Please test proposed solution from https://github.com/proofit404/company-anaconda/tree/improve-prefix-regex

**Comment by Purring** [comment] 2016-12-05 23:44
Works perfectly for me when i tested it against the gist i posted.

**Comment by Purring** [comment] 2016-12-31 03:21
Added another test case i ran into to the gist, it's the __name__ == __main__ unittest one at the bottom

https://gist.github.com/Purring/3c1bf5ff8f5599de4f1090c886d77d17

**Comment by oliveratutexas** [comment] 2017-09-28 15:52
Link for proposed solution is broken, where is it now?

**Comment by vorstrelok** [comment] 2017-11-12 21:35
Hello.

I have the same issue as the OP. I also use anaconda mode through the spacemacs python layer, and when i do 
```
import cv2
cv2.[some-letter-here]|<wait/trigger completion>
                                         ^cursor
```
emacs hangs for a couple of seconds. The only difference is that after the error is displayed i get the auto-completion menu with candidates. OpenCV (cv2) seems to be the only affected package, completion for other packages works fine.

Here is the debug output:
```
Debugger entered--Lisp error: (args-out-of-range 0 1)
  put-text-property(0 1 description "module " "")
#[257 "\300\301\"A\300\302\"A\300\303\"A\300\304\"A\300\305\"A
<---a lot of stuff like the above here--->
```

**Comment by vorstrelok** [comment] 2017-11-12 23:09
I think i resolved my issue in a hacky way:
I added the following code in anaconda-mode.el
in function anaconda-mode-complete-extract-names 
I changed this code
```
             (put-text-property 0 1 'description description name)
             (put-text-property 0 1 'module-path module-path name)
             (put-text-property 0 1 'line line name)
             (put-text-property 0 1 'docstring docstring name)
```
to this:
```
           (when (not (s-blank? name))
             (put-text-property 0 1 'description description name)
             (put-text-property 0 1 'module-path module-path name)
             (put-text-property 0 1 'line line name)
             (put-text-property 0 1 'docstring docstring name)
             )
```
and everything seems to work fine.
Though, auto-completion for cv2 module seems a little bit slow

**Comment by serret887** [comment] 2017-11-21 15:09
I am having the same issue but with a different problem. I am having partially autocompletion with anaconda for example if I
`tweepy.<CMD> `
it autocomplete and play nice with documentation popup etc.
![image](https://user-images.githubusercontent.com/13243265/33079562-eccc5c34-cea3-11e7-9054-7799f1c0c738.png)

but when I type
`tweepy.API(auth).<CMD>` it doesn't and I get the following error when I toggle the buffer
`Debugger entered--Lisp error: (args-out-of-range "a = tweepy.API(auth)." 442 443)
  match-string(0 "a = tweepy.API(auth).")
  company-anaconda-prefix()
  company-anaconda(prefix)
  apply(company-anaconda prefix)
  company--force-sync(company-anaconda (prefix) company-anaconda)
  company--multi-backend-adapter((company-anaconda :with company-yasnippet) prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer twiter.py> #<window 3 on twiter.py> 233 443)
  apply(company-idle-begin (#<buffer twiter.py> #<window 3 on twiter.py> 233 443))
  timer-event-handler([t 23060 14720 102137 nil company-idle-begin (#<buffer twiter.py> #<window 3 on twiter.py> 233 443) nil 0])
`
the funny thing is I enable company-jedi to when I try in teh same point I get 
![image](https://user-images.githubusercontent.com/13243265/33079518-cdd9bf9c-cea3-11e7-991d-6beb4c162b6c.png)

I follow all the documentation in python layer for installing all the dependencies I am having this issue in Windows and in Ubuntu

**Comment by proofit404** [comment] 2018-06-03 01:34
Should be fixed with recent `company-anaconda`.

**Closed by proofit404** 2018-06-03 01:34 UTC
