### ISSUE TITLE
anaconda error when type 'lambda'

### ISSUE THREAD

**Issue by scloudyy** [proofit404/anaconda-mode#156] opened 2016-01-20 03:04 UTC
When I want to use lambda in python file it will always appear 
"error in process filter: apply: Wrong type argument: stringp, ((data . "KeyError('resullt',)") (message . "Server error") (code . -32000))
error in process filter: Wrong type argument: stringp, ((data . "KeyError('resullt',)") (message . "Server error") (code . -32000))"
over and over again, and it will freeze

**Comment by scloudyy** [comment] 2016-01-20 03:05
when I type 'lambda', it whil appear 'invalid syntax', and then is 
'error in process filter: apply: Wrong type argument: stringp, ((data . "KeyError('result',)") (message . "Server error") (code . -32000))
error in process filter: Wrong type argument: stringp, ((data . "KeyError('result',)") (message . "Server error") (code . -32000))'
And these two error repeat rapidly that I can even hardly move cursor.
Other seems fine at the moment, and I have already pip install jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2

**Comment by proofit404** [comment] 2016-01-20 08:12
As it was already discussed in relevant spacemacs issue it is combanation of anaconda-mode and jedi bugs. I will fix it on my side when I will have time to do that. Jedi library fix will be available to anaconda-mode after next public release of this awesome library.

Can you provide Emacs version information, so I ensure that test suite will be setup properly.

Closed as duplicate of #148.

**Closed by proofit404** 2016-01-20 08:12 UTC

**Comment by scloudyy** [comment] 2016-01-20 10:19
- OS: gnu/linux
- Emacs: 24.5.3
- jedi: 0.9

Thank you a lot

**Comment by proofit404** [comment] 2016-01-20 10:46
That's sad. I thought it affect Emacs master branch only. But it clear that this bug affects already released editor versions.

**Comment by scloudyy** [comment] 2016-01-20 11:02
I believe you can fix it, come on!
