### ISSUE TITLE
ImportError: No module named jedi after recent update from melpa

### ISSUE THREAD

**Issue by sivakov512** [proofit404/anaconda-mode#225] opened 2017-02-15 03:11 UTC
After last update from melpa i have errors like this:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/cryptomaniac/.emacs.d/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py2.7.egg/anaconda_mode.py", line 17, in <module>
    from jedi import Script, NotFoundError
ImportError: No module named jedi
```
Jedi installed and updated to its latest release (0.10) in system. But current virtualenv does not contain jedi. Should I install jedi in all my working virtualenvs?

**Comment by iserko** [comment] 2017-02-15 08:45
@cryptomaniac512 probably caused by the sdist for jedi 0.10.0 not being available. The maintainer already has an issue for it https://github.com/davidhalter/jedi/issues/849. Hopefully it will be sorted soon.

**Comment by proofit404** [comment] 2017-02-15 13:22
Yeh, I found this issue after release. Unfortunately there is nothing I can do on my side. For now you can install jedi manually.

```bash
git clone https://github.com/davidhalter/jedi
cd jedi
git checkout v0.10.0
python setup.py sdist
cd dist
PYTHONPATH=$HOME/.emacs.d/anaconda-mode/0.1.7 easy_install -d $HOME/.emacs.d/anaconda-mode/0.1.7 -S $HOME/.emacs.d/anaconda-mode/0.1.7 -a -Z jedi-0.10.0.tar.gz
```
Hope this helps.

**Comment by proofit404** [comment] 2017-02-15 13:24
@cryptomaniac512 anaconda-mode ignore any jedi installations including global and inside virtual environment. This is part of internal design is necessary for tramp related machinery.

**Comment by m3nthal** [comment] 2017-02-21 12:55
@proofit404 thank you for the solution. I had to change it a bit because anaconda-mode was in `.cache` subdirectory:
```
PYTHONPATH=$HOME/.emacs.d/.cache/anaconda-mode/0.1.7 easy_install -d $HOME/.emacs.d/.cache/anaconda-mode/0.1.7 -S $HOME/.emacs.d/.cache/anaconda-mode/0.1.7 -a -Z jedi-0.10.0.tar.gz
```

**Comment by proofit404** [comment] 2017-02-21 13:04
I guess that spacemacs have changed anaconda-mode installation directory.

**Comment by DGalt** [comment] 2017-03-26 22:54
Came across this issue initially as well with new install of spacemacs on new machine. However, I now get this: 
```
anaconda_mode port 42923
127.0.0.1 - - [26/Mar/2017 17:45:41] ================================================================================
Traceback (most recent call last):
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py3.6.egg/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py3.6.egg/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py3.6.egg/anaconda_mode.py", line 49, in <listcomp>
    for definition in f(script)]
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/jedi-0.10.0-py3.6.egg/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/jedi-0.10.0-py3.6.egg/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/jedi-0.10.0-py3.6.egg/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)"}}')
```
This is after following the steps outlined above to manually install Jedi. 

(oddly?) completions seem to work fine for standard library packages. I seem to only get this message when trying to get completions from 3rd party installed packages.

**Comment by proofit404** [comment] 2017-03-27 07:18
Yes, we're waiting for this fix in jedi.

**Comment by raxod502** [comment] 2017-03-29 16:48
For those who use [`no-littering`](https://github.com/tarsius/no-littering), the path is

    ~/.emacs.d/etc/anaconda-mode

rather than

    ~/.emacs.d/anaconda-mode

After making that change, the manual install worked great for me.

**Comment by proofit404** [comment] 2017-03-29 16:53
I provide solution for default settings. If your config change installation path, you need to adapt this script according to your config.

**Comment by ngoonee** [comment] 2017-04-06 01:54
https://github.com/davidhalter/jedi/issues/849 has been closed, but this still seems to be an issue for spacemacs users?

**Comment by proofit404** [comment] 2017-04-06 02:05
Can you provide `*anaconda-mode*` buffer content?

**Comment by ngoonee** [comment] 2017-04-06 02:38
Surprisingly restarting emacs and leaving it for a while worked. Suspect there's some connectivity issues here. Seems to work now.

**Comment by zhexuany** [comment] 2017-04-06 02:53
@naoonee I am still experiencing this issue. How did you figure this out?

**Comment by ngoonee** [comment] 2017-04-06 03:03
I'm.... actually not sure. Just started using spacemacs and trying to fit my python workflow into it (long-time vim user). I just went to the *anaconda-mode* buffer (SPC-b-b) and noticed it was still trying to download things....

**Comment by zhexuany** [comment] 2017-04-06 03:05
@proofit404 The error I got when I try to auto-complete `os`
~~~
Processing dependencies for jedi==0.10.2
Finished processing dependencies for jedi==0.10.2
Finished processing dependencies for anaconda_mode==0.1.8
anaconda_mode port 54856
127.0.0.1 - - [06/Apr/2017 11:02:59] ================================================================================
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/usr/local/lib/python2.7/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/usr/local/lib/python2.7/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/usr/local/lib/python2.7/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "ValueError(\'need more than 0 values to unpack\',)"}}')
~~~

**Comment by zhexuany** [comment] 2017-04-06 03:12
@ngoonee Have you experienced the same traceback before? I am newbie to python layer in spacemacs.

**Comment by zhexuany** [comment] 2017-04-06 04:19
This is a known bug in Jedi side. It seems like the only thing we can do it waiting the fix in Jedi side.

**Comment by freyes** [comment] 2017-10-03 20:57
The NotFoundError exception was removed in 0.11.0 davidhalter/jedi@d6a04b29280faaa4309f97390668cadc3a38a46a

**Comment by DGalt** [comment] 2017-11-14 01:34
Still experiencing this after jedi 0.11.0 update:

from `*anaconda-mode*`
```
anaconda_mode port 34277
127.0.0.1 - - [13/Nov/2017 19:16:20] ================================================================================
Traceback (most recent call last):
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg/anaconda_mode.py", line 30, in wrapper
    return f(Script(source, line, column, path))
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg/anaconda_mode.py", line 50, in wrapper
    for definition in f(script)]
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg/anaconda_mode.py", line 50, in <listcomp>
    for definition in f(script)]
  File "/home/dan/.conda/envs/lab_apps/lib/python3.6/site-packages/jedi/api/classes.py", line 301, in full_name
    path = list(self._path())
  File "/home/dan/.conda/envs/lab_apps/lib/python3.6/site-packages/jedi/api/classes.py", line 180, in _path
    return reversed(list(to_reverse()))
  File "/home/dan/.conda/envs/lab_apps/lib/python3.6/site-packages/jedi/api/classes.py", line 161, in to_reverse
    module_context, = name.infer()
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/dan/.emacs.d/.cache/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "ValueError(\'not enough values to unpack (expected 1, got 0)\',)"}}')
```
Just confirming using up to date jedi: 

```
dan ~ $ ls ~/.emacs.d/.cache/anaconda-mode/0.1.9 
anaconda_mode-0.1.9-py3.6.egg  parso-0.1.0-py3.6.egg
easy-install.pth               service_factory-0.1.5-py3.6.egg
jedi-0.11.0-py3.6.egg
```

**Comment by pawarpooja** [comment] 2017-12-06 19:23
I am getting this error: 
![err_image](https://user-images.githubusercontent.com/29332279/33680875-f2f394fa-dae8-11e7-8b9a-a58b416b8ad7.png)
Please help me!!

**Comment by proofit404** [comment] 2017-12-07 04:49
You are trying to use python language statements inside windows cmd console. You should run `python.exe` or something like that to have `>>>` prompt.

**Comment by pawarpooja** [comment] 2017-12-08 15:42
Thank you @proofit404

**Comment by scottspeidel** [comment] 2018-03-23 07:44
@DGalt did you get this working with jedi 0.11.0?

**Comment by proofit404** [comment] 2018-03-23 07:51
Try to upgrade to the Jedi master branch.

**Comment by scottspeidel** [comment] 2018-03-23 08:02
Thanks @proofit404. I will give it a try.

**Comment by scottspeidel** [comment] 2018-03-23 16:54
I was on anaconda_mode-0.1.8. I upgraded to 0.1.9 and everything just worked. 

` ~/.emacs.d/.cache/anaconda-mode/0.1.9                                                                                                                                                                                  [9:50:29] 
> $ la                                                                                                                                                                                                                            [±master ✓]
total 8
drwxr-xr-x  5 s  staff   170B Mar 23 09:40 anaconda_mode-0.1.9-py3.6.egg/
-rw-r--r--  1 s  staff   114B Mar 23 09:40 easy-install.pth
drwxr-xr-x  5 s  staff   170B Mar 23 09:40 jedi-0.11.1-py3.6.egg/
drwxr-xr-x  4 s  staff   136B Mar 23 09:40 parso-0.1.1-py3.6.egg/
drwxr-xr-x  4 s  staff   136B Mar 23 09:40 service_factory-0.1.5-py3.6.egg/`

Thanks everyone

**Comment by proofit404** [comment] 2018-06-03 01:37
Should be fixed now.

**Closed by proofit404** 2018-06-03 01:37 UTC
