### ISSUE TITLE
Anaconda mode opening new windows with errors

### ISSUE THREAD

**Issue by badders** [proofit404/anaconda-mode#164] opened 2016-02-25 14:48 UTC
Generally the autocompletion seems to be working ok and popping up with correct methods and the documentation, but it constantly opens a new emacs window with:
# status: (:error (error connection-failed failed with code 10061 : host 127.0.0.1 :service 9000))
# point 1

It wouldn't be so bad but focus jumps to that window every time

Emacs 25, 64 bit, latest anaconda-mode, setup is the default spacemacs configuration

**Comment by badders** [comment] 2016-02-25 14:49
New window is titled *anaconda-response* if that helps

**Comment by proofit404** [comment] 2016-02-25 17:55
I need the value of `python-shell-interpreter` and `python-shell-virtualenv-path` variables. Does minibuffer contain some error messages? What is the content of `*anaconda-mode*` buffer?

**Comment by badders** [comment] 2016-02-26 08:04
python-shell-interpreter: ipython
python-shell-virtualenv-path: nil
anaconda-mode buffer contains just: anaconda_mode port 9000

no message in minibuffer

**Comment by badders** [comment] 2016-02-26 08:05
Note I don't set either of those variables myself, they are just the defaults on this system

**Comment by proofit404** [comment] 2016-02-26 08:11
Does this happens when you switch buffers? Does this error happens when you constantly typing within one buffer.

**Comment by proofit404** [comment] 2016-02-26 08:11
Do you use pyenv tool?

**Comment by badders** [comment] 2016-02-26 08:36
Dont use pyenv, the python i have installed is the anaconda distribution from continuum, version 2.5 (latest). This error happens when just opeining one python file and doing something like:

import pandas as pd
import numpy as np

pd.read_ or np.arra and waiting for completion

Usually it works for the first 1 or 2 completions, then fails.

**Comment by proofit404** [comment] 2016-02-26 12:00
Does `M-: (anaconda-mode-running-p)` evaluates to `nil` after 1 or 2 completions?

**Comment by badders** [comment] 2016-02-29 10:30
Nope, after i get the status error window pop up it evaluates to:

(run open listen connect stop)

**Comment by vladimir-vovk** [comment] 2016-06-15 07:43
Same issue appears randomly when I typing...

`
# status: (:error (error connection-failed failed with code 35
 :host 127.0.0.1 :service 9000))
# point: 1
`

emacs 24.5, spacemacs 0.105.21

**Comment by proofit404** [comment] 2016-06-15 10:10
I have no idea what can cause this problem.

**Comment by shackra** [comment] 2016-06-24 17:13
I'm experiencing this as well:

```
# status: (:error (error connection-failed failed with code 111
 :host localhost :service 8118))
```

8118 is the port of my local Privoxy installation, I have it set as a environment variable `http_proxy`.

**Comment by proofit404** [comment] 2016-06-24 17:23
@shackra Set `no_proxy` variable as well to exclude `localhost` from proxy settings.

**Comment by shackra** [comment] 2016-06-24 17:26
For those curious, @proofit404 talks about this https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html

**Comment by proofit404** [comment] 2016-06-24 17:30
Exactly. Thanks for clarification!

**Comment by shackra** [comment] 2016-06-24 17:43
The error persists even thought no_proxy is set and Emacs successfully returns the variable definition with `(getenv "no_proxy")`

**Comment by proofit404** [comment] 2016-06-24 17:53
What is the value of `url-proxy-services` variable?

**Comment by shackra** [comment] 2016-06-24 20:06
```
url-proxy-services is a variable defined in `url-vars.el'.
Its value is (("no_proxy" . "\\(localhost\\|192\\.168\\..*\\..*\\)")
 ("http" . "localhost:8118"))

Original value was nil
```

**Comment by proofit404** [comment] 2016-06-24 21:01
Try to set `no_proxy` to localhost only and see if it works.

**Comment by shackra** [comment] 2016-06-26 01:16
the issue is still alive and kicking, even with the change you requested me to introduce:

```
url-proxy-services is a variable defined in `url-vars.el'.
Its value is (("no_proxy" . "\\(localhost\\)")
 ("http" . "localhost:8118"))

Original value was nil
```

**Comment by proofit404** [comment] 2016-06-26 09:21
No idea how to fix this.

**Comment by shackra** [comment] 2016-06-26 15:34
😵

El 26 de junio de 2016 3:21:23 GMT-06:00, Malyshev Artem <notifications@github.com> escribió:
>No idea how to fix this.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/proofit404/anaconda-mode/issues/164#issuecomment-228592102

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by badders** [comment] 2016-07-02 08:00
Just to add that i also had the no_proxy set for localhost when getting this issue

**Comment by churtado** [comment] 2016-08-06 10:22
I'm also getting this issue

**Comment by aumana** [comment] 2016-08-11 17:59
Same issue using emacs prelude

**Comment by proofit404** [comment] 2016-08-11 18:42
Does anyone have an idea where I can find connection failure codes table?

**Comment by binjo** [comment] 2016-08-12 04:30
FTR, try restart the emacs, which should restart the releated process, the error gone for me, I didn't look into root cause...

**Comment by proofit404** [comment] 2016-08-12 07:36
@binjo you don't need to restart text editor. Just use `M-x (anaconda-mode-stop) RET`

**Comment by 3rd3** [comment] 2016-08-24 15:12
Same problem through some Spacemacs package.

**Comment by xarthurx** [comment] 2017-02-12 21:06
same issue.

**Comment by xarthurx** [comment] 2017-02-12 21:41
Same problem through spacemacs configuration.
And when closing emacs, it shows there are may 127.0.0.1 buffer open that tries to connect with the command (network connection to 127.0.0.1)

**Comment by invokesus** [comment] 2017-02-27 19:45
Having the same problem any suggestions?

**Comment by sulami** [comment] 2017-02-27 19:49
I noticed somewhat severe lag when editing a ~3.5k lines python source file, and the error buffer popping up and stealing focus every couple of words. Both went away when I just nuked ~3k lines from the file, so it might just be a timeout issue when it's trying to lookup autocompletion suggestions or something like that.

**Comment by proofit404** [comment] 2017-02-27 19:50
I can't find any description of the connection error codes used in Emacs. You can help if you research this question.

**Comment by sulami** [comment] 2017-02-27 20:05
I this error code 35 was coming from the syscall, it would be `EDEADALK`, "Resource deadlock would occur". I don't know anything about the internal structure of anaconda-mode, but could it be the case that it's trying to open a connection before a previous one is finished or something similar, causing a conflict? Because I can very quickly reproduce this issue by typing random characters into python files with >3k lines, where everything especially autocompletion starts to take a second or two to return suggestions.

**Comment by proofit404** [comment] 2017-02-27 20:20
I suspect it's come from parallel querying overloaded python process.

**Comment by invokesus** [comment] 2017-02-27 21:07
#190 This is the issue I seem to be facing. It's trying to use the proxy to access localhost even though no_proxy is set. Setting http_proxy to "" works but no_proxy doesn't.

**Comment by skrech** [comment] 2017-02-28 15:43
I have the same problem. However, I think that it's related to anaconda-eldoc-mode.
If I remove (add-hook 'python-mode-hook 'anaconda-eldoc-mode) from my init file everything seems to work OK.

**Comment by proofit404** [comment] 2017-02-28 15:46
Eldoc make queries as you move point. So it is still a problem with parallel queries.

**Comment by eserge** [comment] 2017-03-02 10:58
To me it only happens when I edit large python files. So the suspicion about overloaded python processes seems reasonable.

**Comment by penn201500** [comment] 2017-05-15 12:08
(remove-hook 'anaconda-mode-response-read-fail-hook
                 'anaconda-mode-show-unreadable-response)

seems like solved this problem

https://github.com/syl20bnr/spacemacs/issues/3772

**Comment by skrech** [comment] 2017-05-30 12:19
Just wanted to add that when the problem happens this is what list-processes is showing:

```
127.0.0.1       open    --              --           (network connection to 127.0.0.1)
127.0.0.1<1>    open     *http 127.0... --           (network connection to 127.0.0.1)
127.0.0.1<2>    open     *http 127.0... --           (network connection to 127.0.0.1)
127.0.0.1<3>    open     *http 127.0... --           (network connection to 127.0.0.1)
127.0.0.1<4>    open     *http 127.0... --           (network connection to 127.0.0.1)
127.0.0.1<5>    open     *http 127.0... --           (network connection to 127.0.0.1)
anaconda-mode   run     *anaconda-mode* --           python -c 
import sys, site
site.addsitedir('.')
import anaconda_mode
anaconda_mode.main(sys.argv[1:])
```

When anaconda-mode is working OK (for example without eldoc mode support) there is only one connection opened for the localhost.

**Comment by paddyhoran** [comment] 2017-06-01 13:12
Same issue here.

Fix mentioned by @penn201500 does not work for me, still have the issue.

**Comment by LZGH** [comment] 2017-07-18 08:38
@paddyhoran That doesn't work for me too. I sovle it by revise anaconda-mode.el source file,find "(add-hook 'anaconda-mode-response-read-fail-hook 'anaconda-mode-show-unreadable-response)" and remove it,then you need to recompile anaconda-mode.el or delete anaconda-mode.elc directly,then it worked.

**Comment by paddyhoran** [comment] 2017-07-19 01:50
@LZGH, thanks very much. That worked.

**Comment by shivams** [comment] 2017-10-03 09:17
Instead of `localhost`, try `127.0.0.1` for `no_proxy`. This worked for me.

**Comment by proofit404** [comment] 2018-06-03 01:33
Error messages are not propagated to windows anymore.

**Closed by proofit404** 2018-06-03 01:33 UTC
