### ISSUE TITLE
anaconda-mode does not start with Homebrew installed Python

### ISSUE THREAD

**Issue by jehrhardt** [proofit404/anaconda-mode#154] opened 2016-01-08 08:13 UTC
When I install Python via Homebrew on Mac OS X El Capitan via `brew install python`, starting anaconda-mode fails with the following exception:

```
Collecting anaconda-mode==0.1.1
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: jedi, six, service-factory, anaconda-mode
[31mException:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 242, in move_wheel_files
    name, user=user, home=home, root=root, isolated=isolated
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 192, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both[0m
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
```

I use anaconda-mode through Emacs prelude without any changes. Uninstalling the Homebrew Python solves the problem, since Mac OS X's own Python works fine.

**Comment by proofit404** [comment] 2016-01-10 13:57
This is old known problem with homebrew. Remove prefix setting in dist utils configuration. Duplicate of #113.

**Closed by proofit404** 2016-01-10 13:57 UTC
