### ISSUE TITLE
Wrong type argument: stringp, ((message . "Parse error")

### ISSUE THREAD

**Issue by xuehao** [proofit404/anaconda-mode#149] opened 2015-12-13 15:14 UTC
I wrote some code containing Chinese docs, and occurred following error.
When I delete the Chinese docs, I works normally. Is there something wrong with Unicode?

BTW, I use Spacemacs in Win10. I also test in Ubuntu it works normally with Chinese docs. Maybe it's about win10?

emacs message
```
error in process filter: apply: Wrong type argument: stringp, ((message . "Parse error") (code . -32700))
error in process filter: Wrong type argument: stringp, ((message . "Parse error") (code . -32700))

```

anaconda mode message
```
anaconda_mode port 9000
127.0.0.1 - - [13/Dec/2015 23:08:46] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:08:48] code 400, message Bad request syntax (':\\n        raise\\n","line":24,"column":26,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:08:48] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:08:54] code 400, message Bad request syntax (':\\n        raise\\n","line":15,"column":29,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:08:54] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:08:56] code 400, message Bad request syntax ('e:\\n        raise\\n","line":26,"column":0,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:08:56] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:08:59] code 400, message Bad request syntax ('e:\\n        raise\\n","line":26,"column":0,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:08:59] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:10:46] code 400, message Bad request syntax ('e:\\n        raise\\n","line":26,"column":0,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:10:46] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:10:49] code 400, message Bad request syntax ('e:\\n        raise\\n","line":26,"column":0,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:10:49] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:11:48] code 400, message Bad request syntax ('e:\\n        raise\\n","line":26,"column":0,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:11:48] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:11:51] code 400, message Bad request syntax (':\\n        raise\\n","line":23,"column":20,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:11:51] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 61 (char 60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\providers\basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 46, in __call__
    args = self.load_args(arg)
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 64, in load_args
    parse_error()
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\errors.py", line 31, in parse_error
    raise ServiceException(400, dumps(response))
service_factory.exceptions.ServiceException: (400, '{"error": {"message": "Parse error", "code": -32700}, "id": null, "jsonrpc": "2.0"}')
127.0.0.1 - - [13/Dec/2015 23:11:53] code 400, message Bad request syntax (':\\n        raise\\n","line":17,"column":26,"path":"c:/Users/mike/StickPython/Programming_in_Python/chapter_01/1.3/generate_grid.py"}}POST / HTTP/1.1')
127.0.0.1 - - [13/Dec/2015 23:11:53] ================================================================================
Traceback (most recent call last):
  File "c:\Users\mike\.emacs.d\.cache\anaconda-mode\0.1.1\service_factory\service.py", line 62, in load_args
    args = loads(arg)
  File "c:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "c:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)

```

**Comment by proofit404** [comment] 2015-12-13 16:38
Duplicate of #148.

**Closed by proofit404** 2015-12-13 16:38 UTC
